#!/usr/bin/env bash


i=0
while [ $i -le 19 ]
do
    (( i++ ))
    echo $i
    case $i in
    4)
        echo "bad luck from China"
    ;;
    9)
        echo "bad luck from Japan"
    ;;
    17)
        echo "bad luck from Italy"
    ;;
    esac
done
